#!/bin/bash

# source ~/.dotfiles/gibo/gibo-completion.bash
source /etc/bash_completion.d/docker
# source ~/.dotfiles/vagrant-bash-completion/etc/bash_completion.d/vagrant
# source /etc/bash_completion.d/password-store
# source $HOME/.local/bash_completion.d/hugo.sh
